apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managementingresses.operator.ibm.com
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
spec:
  group: operator.ibm.com
  names:
    kind: ManagementIngress
    listKind: ManagementIngressList
    plural: managementingresses
    singular: managementingress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ManagementIngress is the Schema for the managementingresses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ManagementIngressSpec defines the desired state of ManagementIngress
          properties:
            allowedHostHeader:
              type: string
            cert:
              properties:
                dnsNames:
                  items:
                    type: string
                  type: array
                ipAddresses:
                  items:
                    type: string
                  type: array
                issuer:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                repository:
                  type: string
              required:
              - issuer
              type: object
            config:
              additionalProperties:
                type: string
              type: object
            fipsEnabled:
              type: boolean
            image:
              properties:
                repository:
                  type: string
                tag:
                  type: string
              required:
              - repository
              - tag
              type: object
            imageRegistry:
              type: string
            managementState:
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              type: object
            resources:
              description: ResourceRequirements describes the compute resource requirements.
              properties:
                limits:
                  additionalProperties:
                    type: string
                  description: 'Limits describes the maximum amount of compute resources
                    allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                  type: object
                requests:
                  additionalProperties:
                    type: string
                  description: 'Requests describes the minimum amount of compute resources
                    required. If Requests is omitted for a container, it defaults
                    to Limits if that is explicitly specified, otherwise to an implementation-defined
                    value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                  type: object
              type: object
            routeHost:
              type: string
            tolerations:
              items:
                description: The pod this Toleration is attached to tolerates any
                  taint that matches the triple <key,value,effect> using the matching
                  operator <operator>.
                properties:
                  effect:
                    description: Effect indicates the taint effect to match. Empty
                      means match all taint effects. When specified, allowed values
                      are NoSchedule, PreferNoSchedule and NoExecute.
                    type: string
                  key:
                    description: Key is the taint key that the toleration applies
                      to. Empty means match all taint keys. If the key is empty, operator
                      must be Exists; this combination means to match all values and
                      all keys.
                    type: string
                  operator:
                    description: Operator represents a key's relationship to the value.
                      Valid operators are Exists and Equal. Defaults to Equal. Exists
                      is equivalent to wildcard for value, so that a pod can tolerate
                      all taints of a particular category.
                    type: string
                  tolerationSeconds:
                    description: TolerationSeconds represents the period of time the
                      toleration (which must be of effect NoExecute, otherwise this
                      field is ignored) tolerates the taint. By default, it is not
                      set, which means tolerate the taint forever (do not evict).
                      Zero and negative values will be treated as 0 (evict immediately)
                      by the system.
                    format: int64
                    type: integer
                  value:
                    description: Value is the taint value the toleration matches to.
                      If the operator is Exists, the value should be empty, otherwise
                      just a regular string.
                    type: string
                type: object
              type: array
          required:
          - cert
          - image
          - imageRegistry
          - managementState
          - routeHost
          type: object
        status:
          description: ManagementIngressStatus defines the observed state of ManagementIngress
          properties:
            condition:
              additionalProperties:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              type: object
            host:
              type: string
            operandState:
              properties:
                message:
                  type: string
                status:
                  type: string
              required:
              - message
              - status
              type: object
            podstate:
              additionalProperties:
                items:
                  type: string
                type: array
              type: object
          required:
          - host
          - operandState
          - podstate
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
