apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-management-ingress-operator
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
    name: ibm-management-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-management-ingress-operator
  template:
    metadata:
      labels:
        name: ibm-management-ingress-operator
        app.kubernetes.io/managed-by: "ibm-management-ingress-operator"
        app.kubernetes.io/name: "ibm-management-ingress-operator"
        app.kubernetes.io/instance: ibm-management-ingress-operator
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-management-ingress-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-management-ingress-operator
          image: icr.io/cpopen/ibm-management-ingress-operator:1.20.2
          imagePullPolicy: Always
          command:
          - ibm-management-ingress-operator
          resources:
            limits:
              cpu: 1000m
              memory: 170Mi
            requests:
              cpu: 70m
              memory: 60Mi
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 20
            timeoutSeconds: 3
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ICP_MANAGEMENT_INGRESS_IMAGE
              value: icr.io/cpopen/cpfs/icp-management-ingress:2.6.4
            - name: ROUTE_HTTPS_PORT
              value: ""
            - name: ROUTE_HTTP_PORT
              value: ""
            - name: CLUSTER_NAME
              value: ""
            - name: VERSION
              value: ""
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
