apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ibm-management-ingress-operator
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-management-ingress-operator
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
    name: ibm-management-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-management-ingress-operator
  template:
    metadata:
      labels:
        name: ibm-management-ingress-operator
        app.kubernetes.io/managed-by: "ibm-management-ingress-operator"
        app.kubernetes.io/name: "ibm-management-ingress-operator"
        app.kubernetes.io/instance: ibm-management-ingress-operator
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-management-ingress-operator
      containers:
        - name: ibm-management-ingress-operator
          image: quay.io/opencloudio/ibm-management-ingress-operator:1.4.0
          imagePullPolicy: Always
          command:
          - ibm-management-ingress-operator
          resources:
            limits:
              cpu: 160m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 320Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERAND_IMAGE_DIGEST
              value: quay.io/opencloudio/icp-management-ingress@sha256:fa6650cd65f943d5d3c8c6fd84ae97abdd51396bed9b2ffaae2895b484435e26
            - name: ROUTE_HTTPS_PORT
              value: ""
            - name: ROUTE_HTTP_PORT
              value: ""
            - name: CLUSTER_NAME
              value: ""
            - name: VERSION
              value: ""

