apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-management-ingress-operator
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
    name: ibm-management-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-management-ingress-operator
  template:
    metadata:
      labels:
        name: ibm-management-ingress-operator
        app.kubernetes.io/managed-by: "ibm-management-ingress-operator"
        app.kubernetes.io/name: "ibm-management-ingress-operator"
        app.kubernetes.io/instance: ibm-management-ingress-operator
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-management-ingress-operator
      containers:
        - name: ibm-management-ingress-operator
          image: quay.io/opencloudio/ibm-management-ingress-operator:1.5.1
          imagePullPolicy: Always
          command:
          - ibm-management-ingress-operator
          resources:
            limits:
              cpu: 1000m
              memory: 170Mi
            requests:
              cpu: 70m
              memory: 60Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERAND_IMAGE_DIGEST
              value: quay.io/opencloudio/icp-management-ingress@sha256:6641653b351901eb9352e06479d75a4babaf746bcd63381a09a58d9192b0953c
            - name: ROUTE_HTTPS_PORT
              value: ""
            - name: ROUTE_HTTP_PORT
              value: ""
            - name: CLUSTER_NAME
              value: ""
            - name: VERSION
              value: ""

