# permissions for end users to view managementingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementingress-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - managementingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - managementingresses/status
  verbs:
  - get
